apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app: notifications-MS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-MS
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notifications-MS
    spec:
      containers:
      - name: notifications-container
        image: registry.gitlab.com/gitlabodix/cvtheque-notifications-ms-prod
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
      imagePullSecrets:
      - name: gitlab-secrets-notifications-ms
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-MS
  ports:
    - port: 8004
      targetPort: 8004

