apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app: notifications
spec:
  replicas: 1 #  tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: notifications
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications-container
        image: registry.gitlab.com/gitlabodix/cvtheque-notifications-ms-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
      imagePullSecrets:
      - name: gitlab-secrets-notifications-ms
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - port: 8004
      targetPort: 8004

