apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: notifications-ms
build:
  artifacts:
  - image: registry.gitlab.com/gitlabodix/cvtheque-notifications-ms-prod
deploy:
  kubectl:
    manifests:
    - ks8-local.yml
